# Generated by Django 5.1 on 2024-08-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aluno_turmas_alter_turma_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turmas',
        ),
    ]
