# Generated by Django 5.1 on 2024-09-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_disciplina_curso_alter_turma_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
