# Generated by Django 5.1 on 2024-09-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aluno_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('arquivos', models.FileField(upload_to='')),
                ('data_limite', models.DateField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('data', models.DateField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='core.turma')),
            ],
        ),
    ]
