# Generated by Django 5.1 on 2024-09-29 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_atividade_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_limite',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
